Dropdown elements
observational-dev/oawiki pull request #32
Opened 2023-10-16 13:33 UTC by random-person-001

This implements and demonstrates a dropdown dialog, which could be useful for FAQs or other places in the first parts of the wiki to be viewed by newcomers. I also added in an example wiki page that can be used as a starting point for others and formatting reference. I'd like to retain that even if we decide the dropdown feature is unneeded. For now it's in the imaging/ folder as I had issues putting it elsewhere.

It requires an additonal pip package, `sphinx-togglebutton`

![both dropdowns collapsed](https://cdn.discordapp.com/attachments/576849290354360323/1163468359501889566/image.png)

![one dropdown opened](https://cdn.discordapp.com/attachments/576849290354360323/1163468359896137919/image.png)

![both dropdowns opened](https://cdn.discordapp.com/attachments/576849290354360323/1163468360286220398/image.png)

2023-10-16 22:26 UTC, peytondmurray requested changes
A few minor changes.

2023-10-16 22:26 UTC, peytondmurray commented on src/imaging/examplepage.md
> +# Example Page
Please also link to https://myst-parser.readthedocs.io/en/latest/ or https://myst-parser.readthedocs.io/en/latest/syntax/typography.html#syntax-core, which contains information about extensions to markdown syntax. This is the actual markdown parser we are using.

2023-10-16 22:26 UTC, peytondmurray commented on src/_static/css/custom.css
> +}
If we aren't actually going to customize styles, let's delete these empty rules.

2023-10-16 22:26 UTC, peytondmurray commented on src/_static/css/custom.css
> +  /*color: hsl(0, 100%, 50%);*/
```suggestion
```

2023-10-16 22:26 UTC, peytondmurray commented on src/_static/css/custom.css
> +}
```suggestion
```

2023-10-16 22:26 UTC, peytondmurray commented on src/_static/css/custom.css
> +/* Question dropdown stuff */
```suggestion
/* Custom dropdown stuff */
```

2023-10-17 00:53 UTC, random-person-001 commented
Superseded by #37

2023-10-17 00:53 UTC, closed without merging